const matkulfix: Array<any> = [
  {
    Kode: "IF111",
    MataKuliah: "Kalkulus",
    Kelas: "A",
    SKS: 3,
    AlihKredit: "Tidak",
    NamaDosen: "Mike Johnson",
  },
  {
    Kode: "IF112",
    MataKuliah: "Algoritma dan Pemrograman",
    Kelas: "B",
    SKS: 2,
    AlihKredit: "Ya",
    NamaDosen: "Daniel Thomas",
  },
  {
    Kode: "IF113",
    MataKuliah: "Pemrograman Web",
    Kelas: "C",
    SKS: 3,
    AlihKredit: "Tidak",
    NamaDosen: "Emily Wilson",
  },
];

const matkulfrs: Array<any> = [
  {
    MataKuliah: "Kalkulus",
    Kelas: "A",
    TanggalAmbil: "2021-08-20",
    TanggalProses: "2021-08-21",
    Pengambil: "Mike Johnson",
    Status: 2,
    BerhasilDiambil: "Ya",
  },
  {
    MataKuliah: "Struktur Data",
    Kelas: "B",
    TanggalAmbil: "2021-08-21",
    TanggalProses: "2021-08-22",
    Pengambil: "Alice Smith",
    Status: 4,
    BerhasilDiambil: "Tidak",
  },
  {
    MataKuliah: "Pemrograman Web",
    Kelas: "C",
    TanggalAmbil: "2021-08-22",
    TanggalProses: "2021-08-23",
    Pengambil: "Bob Williams",
    Status: 3,
    BerhasilDiambil: "Tidak",
  },
  {
    MataKuliah: "Basis Data",
    Kelas: "D",
    TanggalAmbil: "2021-08-23",
    TanggalProses: "2021-08-24",
    Pengambil: "Chris Brown",
    Status: 5,
    BerhasilDiambil: "Tidak",
  },
  {
    MataKuliah: "Sistem Operasi",
    Kelas: "E",
    TanggalAmbil: "2021-08-24",
    TanggalProses: "2021-08-25",
    Pengambil: "Emily Wilson",
    Status: 1,
    BerhasilDiambil: "Tidak",
  },
  {
    MataKuliah: "Pemrograman Berorientasi Objek",
    Kelas: "A",
    TanggalAmbil: "2021-08-25",
    TanggalProses: "2021-08-26",
    Pengambil: "Daniel Thomas",
    Status: 2,
    BerhasilDiambil: "Ya",
  },
  {
    MataKuliah: "Rekayasa Perangkat Lunak",
    Kelas: "B",
    TanggalAmbil: "2021-08-26",
    TanggalProses: "2021-08-27",
    Pengambil: "Hannah Miller",
    Status: 3,
    BerhasilDiambil: "Tidak",
  },
];

export { matkulfix, matkulfrs };
